### ISSUE TITLE
Get uptime test history

### ISSUE THREAD

**Issue by DanielWeeber** [chelnak/status-cake-exporter#13]
Any chance you can implement the time the last check of statuscake took?
We could graph out the performance then

https://www.statuscake.com/api/v1/#operation/list-uptime-test-histor
<img width="1285" alt="Bildschirmfoto 2022-01-07 um 19 22 52" src="https://user-images.githubusercontent.com/2935130/148589252-2914185b-1c13-4d83-804c-8bf3e284f43a.png">
<img width="1235" alt="Bildschirmfoto 2022-01-07 um 19 23 06" src="https://user-images.githubusercontent.com/2935130/148589259-2a4d9767-1810-44ea-9808-7beaf2380dae.png">

**Comment by chelnak** [comment]
@DanielWeeber hey! I'm going to be doing some work on the project over the next few weeks so happy to look in to this feature request!

**Comment by AmanDoad1989** [comment]
Was this fixed already?

**Comment by chelnak** [comment]
@AmanDoad1989 no not yet, it's not forgotten.

Contributions are very welcome though if either of you have the time!

**Comment by chelnak** [comment]
@DanielWeeber We are doing soy work on the exporter so happy to look at this.

**Comment by chelnak** [comment]
Hey @DanielWeeber @AmanDoad1989 @Jeff-SearchPilot !

I've added the performance metric from the uptime history api. It's available to test in the latest dev image if you want to take it for a spin.

```
# HELP status_cake_test_performance Tests and their performance
# TYPE status_cake_test_performance gauge
status_cake_test_performance{test_id="123"} 579.0

....

# HELP status_cake_test_info A basic listing of the tests under the current account.
# TYPE status_cake_test_info gauge
status_cake_test_info{maintenance_status_int="0",test_id="123",test_name="example HTTP check",test_performance="579.0",test_status_int="0",test_type="HTTP",test_uptime_percent="99.9",test_url="https://www.example.com"} 0.0

```

**Comment by Jeff-SearchPilot** [comment]
Thanks @chelnak, I've started looking at this but running into some issues. I've raised #28 to fix one but the bigger issue is the rate limiting being imposed by statuscake. With the performance data being collected the app is now making an additional API request for each test detected, this quickly hits the pretty low [rate limits](https://developers.statuscake.com/guides/api/ratelimiting/), even on paid accounts. It doesnt look like the statuscake library implements any kind of backoff mechanism natively, is this something that could be implemented in `status-cake-exporter`?

It might also be worth making the performance data an optional feature - the rate limiting may well cause problems for those not using it.

**Comment by chelnak** [comment]
Good catch and thank you for the PR.

We can certainly look at some form of rate limit support.

I would expect the status cake api to return the right status code for a rate limit event, so we should be able to handle it.

WRT it being an optional feature, what would work best? Off by default or On?

**Comment by Jeff-SearchPilot** [comment]
I'm just playing around with seeing how best to handle rate limit events, it might be pretty straightforward. Ill pop another PR later if it all goes to plan.

As to it being optional - I'd say leave if off by default since this would mimic the previous behavior (and not break anything)

**Comment by chelnak** [comment]
@Jeff-SearchPilot After your latest PR, i think we can close this issue now right?

**Comment by Jeff-SearchPilot** [comment]
Yep, its all working now :smiley:

**Comment by chelnak** [comment]
Great news. Thanks so much for your help. Have a wonderful week!
