### ISSUE TITLE
V1 endpoints don't template in helm correctly

### ISSUE THREAD

**Issue by grrywlsn** [chelnak/status-cake-exporter#15]
Helm (via Flux's HelmRelease CRD) wasn't able to parse the boolean values for the V1 environment variables.  I've swapped to putting them in quotes, which parses fine and allows the helm chart to install.

A sample of the error:

```
Helm install failed: Deployment in version "v1" cannot be handled as a Deployment: v1.Deployment.Spec: v1.DeploymentSpec.Template: v1.PodTemplateSpec.Spec: v1.PodSpec.Containers: []v1.Container: v1.Container.Env: []v1.EnvVar: v1.EnvVar.Value: ReadString: expects " or n, but found t, error found in #10 byte of ...|,"value":true},{"nam|..., bigger context ...|"env":[{"name":"USE_V1_UPTIME_ENDPOINTS","value":true},{"name":"USERNAME","valueFrom":{"secretKeyRef|...
```

I've raised #14 with a fix that I've tested, and which resolved this issue. Thanks for the great project!

**Comment by chelnak** [comment]
Thanks so much for submitting this & a fix!
