### ISSUE TITLE
402 Client Error: Payment Required

### ISSUE THREAD

**Issue by mrpandat** [chelnak/status-cake-exporter#17]
Hello, thank you for the amazing work on this project. :)

I have tried to run the project via docker: `docker run -d -p 8000:8000 --env USERNAME --env API_KEY --env USE_V1_MAINTENANCE_WINDOWS_ENDPOINTS ghcr.io/chelnak/status-cake-exporter:latest`, but the image crashes after only a couple of seconds with this error:
`2022-10-14 13:28:53,029 - status_cake_client.maintenance - ERROR - 402 Client Error: Payment Required for url: https://app.statuscake.com/API/Maintenance?state=ACT
`

I don't understand, because the variable USE_V1_MAINTENANCE_WINDOWS_ENDPOINTS is false by default, and this is not supposed to contact de /Maintenance api.

Do you know how to avoid this error ?
Thank you very much

**Comment by mrpandat** [comment]
A workaround would be something like: https://github.com/mrpandat/status-cake-exporter/commit/7bdceb5ffcf1b644fbbddc09bffefa9c5e471691

**Comment by chelnak** [comment]
Hello! Thanks for posting the issue!

Would you like to submit your patch as a PR? It seems like a reasonable fit to me.

😊

**Comment by chelnak** [comment]
Also cc @jack-cloud-platform as he  was the author of this feature.

**Comment by jack-cloud-platform** [comment]
@mrpandat what's the behaviour when the variable is true?

StatusCake are in the process of deprecating their legacy API, moving users to 'v1'.

https://www.statuscake.com/kb/knowledge-base/api-migration-guide/ describes how a given StatusCake account can use the legacy maintenance windows endpoints or non-legacy but not both.

**Comment by mrpandat** [comment]
Hello @jack-cloud-platform & @chelnak and thank you for the quick answers 🙏 

@jack-cloud-platform -> no difference. Am I doing this right ? 

`USE_V1_MAINTENANCE_WINDOWS_ENDPOINTS=true
docker run -d -p 8000:8000 --env USERNAME --env API_KEY --env USE_V1_MAINTENANCE_WINDOWS_ENDPOINTS ghcr.io/chelnak/status-cake-exporter:latest`

docker logs: `2022-10-19 07:59:47,787 - status_cake_client.maintenance - ERROR - 402 Client Error: Payment Required for url: https://app.statuscake.com/API/Maintenance?state=ACT`

**Comment by mrpandat** [comment]
Hello @jack-cloud-platform, did you had a chance to look this issue ? Thank you :)

**Comment by jack-cloud-platform** [comment]
> Hello @jack-cloud-platform, did you had a chance to look this issue ? Thank you :)

Hi @mrpandat, are you on a free plan? The maintenance windows endpoints require non-free plans, old doc link https://www.statuscake.com/api/Maintenance%20Windows/Create%20Maintenance%20Window.md#:~:text=HTTP%20402%20%2D%20Payment%20Required%20%2D%20You,your%20account%20for%20more%20information.

I'll work with @chelnak on an update with the option to not call the maintenance windows endpoints

**Comment by chelnak** [comment]
Hey! v1 has now been released and this should now be resolved!

https://github.com/chelnak/status-cake-exporter/releases/tag/v1.0.0
