### ISSUE TITLE
 ERROR - 500 Server Error: Internal Server Error for url: https://api.statuscake.com/v1/uptime?page=1

### ISSUE THREAD

**Issue by abhinavstax** [chelnak/status-cake-exporter#18]
Hello, 

This is an amazing project. Lately, we found Internal Server Errors on using this tool.

We are scraping the metrics every 30s and lately, we have frequently observed this error making us lose some metrics. 
Can this issue be looked into and a solution be proposed?

**Comment by abhinavstax** [comment]
Hello @chelnak did you get a chance to look at it?

I am also observing this error as well

status_cake_client.maintenance - ERROR - 504 Server Error: Gateway Timeout for url: https://api.statuscake.com/v1/maintenance-windows?state=active

**Comment by chelnak** [comment]
Hey @abhinavstax, these look like they are coming from the status cake api itself.

Do you see any outages reported for status cake at the time you received the errors?

Does it completely crash the exporter?

@jack-cloud-platform have you noticed similar errors in your logs?

**Comment by abhinavstax** [comment]
Do you see any outages reported for status cake at the time you received the errors?
No. 

Does it completely crash the exporter?
yes, it does as there is no exception handling at the get function when making the API call to the statuscake.

**Comment by chelnak** [comment]
Hey, thanks for the quick response!

We are open to PRs if this is something that you'd be interested in fixing?

**Comment by abhinavstax** [comment]
@chelnak Raised a PR https://github.com/chelnak/status-cake-exporter/pull/21/files . can you review

**Comment by chelnak** [comment]
Hello! Thanks so much for this. I'll get it reviewed asap.

Meanwhile, if you are interested in testing we are working on a new version of the exporter here: https://github.com/chelnak/status-cake-exporter/pull/20

Thanks!

**Comment by chelnak** [comment]
Hey v1 has been released and this should now be resolved!

https://github.com/chelnak/status-cake-exporter/releases/tag/v1.0.0
