### ISSUE TITLE
Error while fetching maintenance window

### ISSUE THREAD

**Issue by martindaehn23** [chelnak/status-cake-exporter#24]
Hey that is an awesome project! Unfortunately I can't get it working,
as i ran into the following issue:
```
2023-06-09 12:03:58,838 - test_collector - INFO - Collector started.
2023-06-09 12:03:59,082 - status_cake - ERROR - Error while fetching maintenance windows: Invalid value for `total_count`, must be a value greater than or equal to `1`
2023-06-09 12:03:59,082 - test_collector - CRITICAL - A fatal error occurred: Invalid value for `total_count`, must be a value greater than or equal to `1`
2023-06-09 12:03:59,084 - test_collector - INFO - Collector finished.
```
Can this issue be looked into and a solution be proposed? Thanks in advance!

**Comment by ekalaya2021** [comment]
I have same issue. @martindaehn23 did you resolve your problem

**Comment by chelnak** [comment]
I don't have the environment to debug this right now but happy to accept PRs if you find that there is an issue!

**Comment by martindaehn23** [comment]
No i looked a bit into it, but it seems like this project is just not too maintained any more ... Statuscake now offers https://github.com/StatusCakeDev/statuscake-py whereas this project uses some older module. @chelnak correct me if I am wrong... So I guess somebody would need to implement this "new" statuscake python sdk. Unfortunately my Python knowledge is not enough for doing that... That's is really a pitty, because i would love to use this exporter if it would work.
For the question, if this value is in the payload @chelnak how can i view the payload. I set the container to debug, but i can't see the payload, only the exception. When i test it with statuscake-py i can see the total_count in the response:
```
...
           'website_url': 'https://<example>'}],
 'metadata': {'page': 1, 'page_count': 3, 'per_page': 25, 'total_count': 57}}
 ```

**Comment by chelnak** [comment]
I'm sure we looked at using the official library when it was released.

IIRC there isn't a way to make it show you the payloads unless you add some additional logging in to the code.

The project is not-not maintained atm, it just reached a point where it worked for the original use case. I guess time has got in the way of me doing anything with it in recent months.

It would be nice to integrate the statuscake sdk especially if it helps out users of the exporter.

I can take a look at this at some point or @CloudPlatformer (who helped with a big refactor) might be able to take a look sooner!

**Comment by chelnak** [comment]
OK so I have a bit more context for you.

We use statuscake-py but it looks like we are now a few versions behind.

The issue you are seeing was actually a bug in their SDK. I logged [this issue](https://github.com/StatusCakeDev/statuscake-py/issues/8) and we also tried to work around it in v1 (but that obviously isn't reliable).

I will publish a new image with updated packages - would you be able to test this at some point?

**Comment by chelnak** [comment]
Here is a dev image to test: 

`docker pull ghcr.io/chelnak/status-cake-exporter:dev`

Let me know how you get on. It's based on PR #26

**Comment by chelnak** [comment]
Closing - pretty sure this is fixed.

Please do open another issue if there are still issues.
